grpc:
  enabled: true
  server:
    port: 9090
    security:
      enabled: true
      certificate-chain: classpath:certificate.pem
      private-key: classpath:private.key
    http2:
      enabled: true
